

//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ConsoleApp1
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GesComEntities1 : DbContext
{
    public GesComEntities1()
        : base("name=GesComEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<tb_maquinario> tb_maquinario { get; set; }

}

}

