//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_chamados
    {
        public int cha_id { get; set; }
        public int usu_id { get; set; }
        public string cha_descricao { get; set; }
        public System.DateTime cha_dataAbertura { get; set; }
        public System.DateTime cha_dataFinalizacao { get; set; }
        public string cha_anexo { get; set; }
        public string cha_titulo { get; set; }
        public Nullable<int> emp_id { get; set; }
    
        public virtual tb_empresasManutencao tb_empresasManutencao { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
