//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cidades
    {
        public tb_cidades()
        {
            this.tb_localizacao = new HashSet<tb_localizacao>();
        }
    
        public int cid_id { get; set; }
        public string cid_nome { get; set; }
        public string cid_uf { get; set; }
        public Nullable<int> est_id { get; set; }
    
        public virtual tb_estado tb_estado { get; set; }
        public virtual ICollection<tb_localizacao> tb_localizacao { get; set; }
    }
}
