//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresasManutencao
    {
        public tb_empresasManutencao()
        {
            this.tb_chamados = new HashSet<tb_chamados>();
        }
    
        public int emp_id { get; set; }
        public string emp_nome { get; set; }
        public string emp_telefone { get; set; }
        public string emp_endereco { get; set; }
        public string emp_CEP { get; set; }
        public string emp_CNPJ { get; set; }
        public string emp_rua { get; set; }
        public string emp_bairro { get; set; }
        public Nullable<int> cid_id { get; set; }
        public Nullable<int> est_id { get; set; }
    
        public virtual ICollection<tb_chamados> tb_chamados { get; set; }
    }
}
