//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estado
    {
        public tb_estado()
        {
            this.tb_cidades = new HashSet<tb_cidades>();
        }
    
        public int est_id { get; set; }
        public string est_nome { get; set; }
        public string est_uf { get; set; }
    
        public virtual ICollection<tb_cidades> tb_cidades { get; set; }
    }
}
