//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_licencas
    {
        public tb_licencas()
        {
            this.tb_relacionamentos = new HashSet<tb_relacionamentos>();
        }
    
        public int lic_id { get; set; }
        public string lic_nomeFabricante { get; set; }
        public string lic_nomeProduto { get; set; }
        public Nullable<double> lic_valor { get; set; }
        public string lic_serial { get; set; }
        public Nullable<System.DateTime> lic_dataCompra { get; set; }
        public Nullable<System.DateTime> lic_dataExpiracao { get; set; }
    
        public virtual ICollection<tb_relacionamentos> tb_relacionamentos { get; set; }
    }
}
