//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_localizacao
    {
        public tb_localizacao()
        {
            this.tb_relacionamentos = new HashSet<tb_relacionamentos>();
        }
    
        public int loc_id { get; set; }
        public Nullable<int> maq_id { get; set; }
        public Nullable<int> cid_id { get; set; }
        public Nullable<System.DateTime> loc_dataInclusao { get; set; }
    
        public virtual tb_cidades tb_cidades { get; set; }
        public virtual ICollection<tb_relacionamentos> tb_relacionamentos { get; set; }
    }
}
