//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_maquinario
    {
        public tb_maquinario()
        {
            this.tb_relacionamentos = new HashSet<tb_relacionamentos>();
        }
    
        public string maq_nome { get; set; }
        public string maq_procNome { get; set; }
        public string maq_memoriaRam { get; set; }
        public string maq_memoriaHD { get; set; }
        public string maq_sisOperacional { get; set; }
        public string maq_placaVideo { get; set; }
    
        public virtual ICollection<tb_relacionamentos> tb_relacionamentos { get; set; }
    }
}
