//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mobilias
    {
        public int mob_id { get; set; }
        public string mob_descricao { get; set; }
        public double mob_valor { get; set; }
        public System.DateTime mob_dataCompra { get; set; }
        public int mob_qtde { get; set; }
    }
}
