//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_perifericos
    {
        public tb_perifericos()
        {
            this.tb_relacionamentos = new HashSet<tb_relacionamentos>();
        }
    
        public int per_id { get; set; }
        public string per_descricao { get; set; }
        public Nullable<System.DateTime> per_dataAquisicao { get; set; }
        public Nullable<double> per_valor { get; set; }
    
        public virtual ICollection<tb_relacionamentos> tb_relacionamentos { get; set; }
    }
}
