//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_relacionamentos
    {
        public int rel_id { get; set; }
        public string maq_id { get; set; }
        public Nullable<int> usu_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public Nullable<int> lic_id { get; set; }
        public Nullable<int> loc_id { get; set; }
    
        public virtual tb_licencas tb_licencas { get; set; }
        public virtual tb_localizacao tb_localizacao { get; set; }
        public virtual tb_maquinario tb_maquinario { get; set; }
        public virtual tb_perifericos tb_perifericos { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
